# Generated by Django 5.2.3 on 2025-06-23 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_comment_updated_post_content_pos_created_1233b3_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Post Title', max_length=255),
            preserve_default=False,
        ),
    ]
