# Generated by Django 5.2.3 on 2025-06-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/post_images/default.jpg', null=True, upload_to='post_images/'),
        ),
    ]
