# Generated by Django 5.2.3 on 2025-07-22 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0014_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='media/blog_images/b_default.webp', null=True, upload_to='blog_images/'),
        ),
    ]
