# Generated by Django 5.2.3 on 2025-07-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0015_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, default='blog_images/b_default.webp', null=True, upload_to='blog_images/'),
        ),
    ]
