# Generated by Django 5.2.3 on 2025-07-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0016_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='post_images/default.webp', null=True, upload_to='post_images/'),
        ),
    ]
