# Generated by Django 5.2.3 on 2025-07-02 09:16

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('service_type', models.CharField(choices=[('vet', 'Veterinarian'), ('grooming', 'Grooming'), ('walking', 'Dog Walking'), ('boarding', 'Boarding / Pet Sitting'), ('training', 'Training'), ('breeding', 'Breeding'), ('nutrition', 'Nutrition / Diet Consultation'), ('insurance', 'Pet Insurance'), ('photography', 'Pet Photography'), ('transport', 'Pet Transport'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_images/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
