# Generated by Django 5.2.3 on 2025-06-18 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_alter_blog_options_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ['-id']},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'blog')},
        ),
        migrations.AddField(
            model_name='rating',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.post'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='content.blog'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'blog'), ('user', 'post')},
        ),
    ]
