# Generated by Django 5.2.3 on 2025-06-23 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_rating_options_alter_rating_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
