# Generated by Django 5.2.3 on 2025-07-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_message', 'New Message'), ('new_comment', 'New Comment'), ('affiliate_clicked', 'Affiliate Link Clicked')], max_length=20),
        ),
    ]
