# Generated by Django 5.2.3 on 2025-07-03 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('comment', 'New Comment'), ('affiliate_click', 'Affiliate Link Clicked')], max_length=20),
        ),
    ]
