# Generated by Django 5.2.3 on 2025-08-06 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
