# Generated by Django 5.2.3 on 2025-09-10 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_read_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_sender__fd66f3_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='messaging_m_receive_5b2f13_idx',
        ),
    ]
