# Generated by Django 5.2.3 on 2025-09-11 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0006_remove_message_messaging_m_sender__fd66f3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver', '-sent_at'], name='messaging_m_sender__fd66f3_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_read', '-sent_at'], name='messaging_m_receive_91fbfb_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_deleted_by_sender', 'is_deleted_by_receiver'], name='messaging_m_is_dele_998a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'is_deleted_by_receiver'], name='messaging_m_receive_be4ebd_idx'),
        ),
    ]
