# Generated by Django 5.2.3 on 2025-08-06 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('message', 'New Message'), ('comment', 'New Comment'), ('affiliate_click', 'Affiliate Link Clicked'), ('rating_given', 'Rating Given')], max_length=20),
        ),
    ]
