# Generated by Django 5.2.3 on 2025-08-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_myuser_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.webp', null=True, upload_to='profile_images/'),
        ),
    ]
